name: Diabetic_Retinopathy_Scanner
description: A Mobile Application Developed for Diagnosis of Diabetic Retinopathy Disease

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^0.3.2
  path_provider: ^1.6.1
  cupertino_icons: ^0.1.2
  tflite: ^1.0.4
  image_picker: ^0.6.2+3
  image: ^2.1.4
  circular_bottom_navigation: ^1.0.1
  flutter_launcher_icons: ^0.7.5
  camera: ^0.5.7+4
  video_player: ^0.10.10



flutter_icons:
  image_path: "assets/logoicon.png"  
  ios: true
  android: true


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/home_background.jpg 
    - assets/images/splashscreen.jpg
    - assets/images/back1.jpg
    - assets/images/logoicon.png
    - assets/tflite/model_unquant.tflite
    - assets/tflite/labels.txt
    - assets/images/splashScreen.jpg
